### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by zhlfmyzhh** [njkrichardson/cdvae#2]
Thank you for your efforts! I installed with Anaconda and met with the following errors: 

First, when using the command

```
pip install --no-index torch_geometric pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-1.13.0+cu116.html
```

It showed that

```
ERROR: Could not find a version that satisfies the requirement torch_geometric (from versions: none)
ERROR: No matching distribution found for torch_geometric
```

The reason is that `torch_geometric` is not in the link `https://data.pyg.org/whl/torch-1.13.0+cu116.html`. Instead, I installed it by

```
pip uninstall numpy
pip install numpy==1.24.4
pip install --no-index pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-1.13.0+cu116.html
pip install torch_geometric==2.0.4
```

I specify the version of `numpy` so that we can install `pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv`. Besides, I specify the version of `torch_geometric`, otherwise, it will cause a problem of `from torch_geometric.nn.acts import swish`. May you check if it is correct?

Then I followed your further installation instructions, and I also use the command to build the cdvae:

```
pip install -e .
```

Finally, I trained the model with `python3 cdvae/run.py data=perov expname=perov`, and this error occurred:

```
Traceback (most recent call last):
  File "/raid/data_stuzhangl/anaconda3/envs/cdvae6/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
    return target(*args, **kwargs)
  File "/raid/data_stuzhangl/GitHub/cdvae_ori/cdvae/pl_modules/gnn.py", line 327, in __init__
    super(DimeNetPlusPlusWrap, self).__init__(
  File "/raid/data_stuzhangl/GitHub/cdvae_ori/cdvae/pl_modules/gnn.py", line 223, in __init__
    self.rbf = BesselBasisLayer(num_radial, cutoff, envelope_exponent)
  File "/raid/data_stuzhangl/anaconda3/envs/cdvae6/lib/python3.9/site-packages/torch_geometric/nn/models/dimenet.py", line 59, in __init__
    self.reset_parameters()
  File "/raid/data_stuzhangl/anaconda3/envs/cdvae6/lib/python3.9/site-packages/torch_geometric/nn/models/dimenet.py", line 62, in reset_parameters
    torch.arange(1, self.freq.numel() + 1, out=self.freq).mul_(PI)
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.
```

I think you do not change the codes of `gnn.py`, is it the problem of `PyTorch` or other stuff? Could you tell me how you succeeded and how to fix the problem?

Thanks again for your work and helps!

**Comment by liusulin** [comment]
what is your PyTorch version? For me it works with `pytorch 1.13.0` build `py3.9_cuda11.6_cudnn8.3.2_0`

**Comment by newalexander** [comment]
@zhlfmyzhh I also experienced this error when executing
```
pip install --no-index torch_geometric pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-1.13.0+cu116.html
```

However, I don't think `torch_geometric==2.0.4` works with the remainder of the current version of this package, as it does not have the `nn.resolver` module (https://github.com/pyg-team/pytorch_geometric/tree/2.0.4/torch_geometric/nn), which is imported in the `gnn` module (https://github.com/njkrichardson/cdvae/blob/master/cdvae/pl_modules/gnn.py#L14).
