### ISSUE TITLE
error message in evaluation script `compute_metrics.py`

### ISSUE THREAD

**Issue by liusulin** [njkrichardson/cdvae#3]
When running `compute_metrics.py`, I encountered the following error message 

```
Traceback (most recent call last):
  File "/home/sulinl/cdvae/scripts/compute_metrics.py", line 16, in <module>
    from matminer.featurizers.site.fingerprint import CrystalNNFingerprint
  File "/home/sulinl/miniconda3/envs/cdvae/lib/python3.9/site-packages/matminer/featurizers/site/__init__.py", line 9, in <module>
    from matminer.featurizers.site.fingerprint import (
  File "/home/sulinl/miniconda3/envs/cdvae/lib/python3.9/site-packages/matminer/featurizers/site/fingerprint.py", line 32, in <module>
    cn_motif_op_params = yaml.safe_load(f)
  File "/home/sulinl/miniconda3/envs/cdvae/lib/python3.9/site-packages/ruamel/yaml/main.py", line 1105, in safe_load
    error_deprecation('safe_load', 'load', arg="typ='safe', pure=True")
  File "/home/sulinl/miniconda3/envs/cdvae/lib/python3.9/site-packages/ruamel/yaml/main.py", line 1037, in error_deprecation
    raise AttributeError(s)
AttributeError: 
"safe_load()" has been removed, use

  yaml = YAML(typ='safe', pure=True)
  yaml.load(...)

instead of file "/home/sulinl/miniconda3/envs/cdvae/lib/python3.9/site-packages/matminer/featurizers/site/fingerprint.py", line 32

    cn_motif_op_params = yaml.safe_load(f)
```
This happens with `ruamel-yaml==0.18.5`, which should be resolved by downgrading `rualmel-yaml` to `ruamel-yaml==0.17.32`.

**Comment by pewkim123** [comment]
it works. thank you sir
